spring:
  servlet:
    multipart:
      max-file-size: 1073741824
      max-request-size: 1073741824
      enabled: true
  application:
    name: inlive-file-manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${application.keycloak-url}/realms/${application.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}
server:
  error:
    include-message: always
  port: ${PORT:8888}
  address: 0.0.0.0
application:
  realm: ${KEYCLOAK_REALM}
  keycloak-url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
  config:
    max-upload-count: 1000
    max-request-size: ${MAX_REQUEST_SIZE:1073741824}  #1gb
    max-in-mem-size: ${MAX_IN_MEM_SIZE:1073741824}  #1gb
aws:
  region: eu-central-1
  s3:
    bucket: ${AWS_BUCKET:test}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    s3_end-pont: https://storage.yandexcloud.kz

management:
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always
    beans:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
